name: Auto Increment Version Tag

on:
  push:
    branches:
      - master  # Trigger only on merges to master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Determine Version Increment
        id: determine_increment
        run: |
          increment_type="patch"
          commit_message=$(git log -1 --pretty=%B)

          if [[ "$commit_message" == *"BREAKING CHANGE:"* ]]; then
            increment_type="major"
          elif [[ "$commit_message" == *"feat:"* ]]; then
            increment_type="minor"
          elif [[ "$commit_message" == *"fix:"* ]]; then
            increment_type="patch"
          fi

          echo "Increment type: $increment_type"
          echo "increment_type=$increment_type" >> $GITHUB_ENV

      - name: Increment the Version
        id: increment_version
        run: |
          IFS='.' read -r major minor patch <<< "${{ env.latest_tag#v }}"

          case "${{ env.increment_type }}" in
            major) major=$((major + 1)); minor=0; patch=0 ;;
            minor) minor=$((minor + 1)); patch=0 ;;
            patch) patch=$((patch + 1)) ;;
          esac

          new_tag="v${major}.${minor}.${patch}"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Check if Tag Already Exists
        run: |
          if git rev-parse "${{ env.new_tag }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.new_tag }} already exists. Exiting..."
            exit 0
          fi

      - name: Push the New Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
